---
apiVersion: batch/v1
kind: Job
metadata:
  name: parallel job
spec:
  completions: 10
  parallelism: 5
  template:
    metadata:
      name: job
      labels:
        type: job
    spec:
      containers: 
        - image: alpine:3
          name: myalpine
          command:
            - sleep
            - 5s
