---
apiVersion: v1
kind: Pod
metadata:
  name: request-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "1000m"
          memory: "1000Mi" 