---
apiVersion: v1
kind: Pod
metadata:
  name: request-pod
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"  
